language: node_js

node_js:
  - 14.5

env:
  - PORT=3000

stages:
  - compile
  - test

jobs:
  install: npm install
  include:
    - stage: compile
      name: "compile typescript to javascript"
      script: npm run build

    - stage: test
      name: "testing code"
      script: npm test  
