language: node_js

node_js:
  - 14.5

env:
  - PORT=3000

stages:
  - install
  - compile
  - test

jobs:
  include:
    - stage: install
      name: "install dependencies"
      install: npm install
    - stage: compile
      name: "compile typescript to javascript"
      script: npm run build
    - stage: test
      name: "testing code"
      script: npm test  
